### ISSUE TITLE
Scaling Factor

### ISSUE THREAD

**Issue by logicraju** [andreasBihlmaier/FusionSDF#1]
Hi,
First of all, thanks for this wonderful tool. In this file: 

"FusionSDF/fusionsdf/link.py"

why is the variable 

`self.scale: float = 0.01  # cm to m`

specified as 0.01 ? Does this tool expect the fusion360 model to be defined in centimetres rather than millimetres?

Regards

**Comment by andreasBihlmaier** [comment]
My understanding is that the Fusion 360 API, which FusionSDF leverages, uses the Fusion 360 "database units" and these are
- Lengths - Centimeters (cm)
- Angles - Radians (rad)
- Mass - Kilograms (kg)
Cf. [Understanding Units in Fusion](https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-A81B295F-984A-4039-B1CF-B449BEE893D7)

Hence the scaling factor is a constant to convert cm (Fusion 360 unit) to m ([ROS unit](https://www.ros.org/reps/rep-0103.html)).

**Comment by logicraju** [comment]
Thank you for the explanation!
